# This workflow will do a clean install of all dependencies,
# run the linter to check for issues and the build the source code as a test.

name: Status checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "yarn"
      - run: yarn
      - run: yarn lint
